name: CQL Migration Runner - AstraDB (PoC)

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - "pom.xml"
      - ".github/workflows/migrate.yml"
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Recreate Secure Connect Bundle
        shell: bash
        env:
          ASTRA_SCB_BASE64: ${{ secrets.ASTRA_SCB_BASE64 }}
        run: |
          set -euo pipefail
          mkdir -p .astra
          echo "$ASTRA_SCB_BASE64" | base64 -d > .astra/secure-connect.zip
          echo "ASTRA_SCB_PATH=$(pwd)/.astra/secure-connect.zip" >> $GITHUB_ENV
          ls -la .astra/secure-connect.zip

      - name: Validate keyspace
        shell: bash
        env:
            ASTRA_DB_KEYSPACE: ${{ secrets.ASTRA_DB_KEYSPACE }}
        run: |
            set -euo pipefail
            echo "Keyspace: '${ASTRA_DB_KEYSPACE}'"
            if [[ -z "${ASTRA_DB_KEYSPACE}" ]]; then echo "ERROR: empty keyspace" && exit 1; fi
            if [[ ! "${ASTRA_DB_KEYSPACE}" =~ ^[A-Za-z0-9_]+$ ]]; then
             echo "ERROR: keyspace must be alphanumerics/underscore only" && exit 1
            fi
      - name: Debug - show compiled classes
        shell: bash
        run: |
            set -euo pipefail
            find src/main/java -maxdepth 4 -type f -name "*.java" -print

      - name: Run migrations
        shell: bash
        env:
            ASTRA_DB_KEYSPACE: ${{ secrets.ASTRA_DB_KEYSPACE }}
            ASTRA_DB_TOKEN: ${{ secrets.ASTRA_DB_TOKEN }}
            ASTRA_SCB_PATH: ${{ env.ASTRA_SCB_PATH }}
        run: |
            set -euo pipefail
            mvn -q -DskipTests clean package
            mvn -q -DskipTests exec:java -Dexec.mainClass=poc.Migrate


